apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.11.0 (39ad614)
  creationTimestamp: null
  labels:
    io.kompose.service: analysis-service
  name: analysis-service
spec:
  replicas: 1
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        io.kompose.service: analysis-service
    spec:
      containers:
      - command:
        - /go/analysis-service
        image: analysis-service
        name: analysis-service
        resources: {}
      restartPolicy: Always
status: {}
