version: '2'
services:
  redis:
    image: redis:alpine

  client:
    depends_on:
      - redis
    build:
      context: "./web_service"
    ports:
      - "8080:8080"
    entrypoint: /go/web-service
  twitter-service:
    build:
      context: "./twitter_service"
    depends_on:
        - redis
    ports:
      - "10000:10000"
    entrypoint: /go/twitter-service
  analysis-service:
    build:
      context: "./analysis_service"
    depends_on:
        - redis
    ports:
      - "6379:6379"
    entrypoint: /go/analysis-service

