version: '2'

services:
  redis:
    image: redis:alpine
    ports:
      - "6379:6379"

  twitter-service:
    build:
      context: "./twitter_service"
    ports:
      - "3000:3000"
    entrypoint: /go/twitter-service

  analysis-service:
    build:
      context: "./analysis_service"
    links:
        - redis
    entrypoint: /go/analysis-service

  client:
    build:
      context: "./web_service"
    ports:
      - "8080:8080"
    links:
        - redis
    entrypoint: /go/web-service
