apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.11.0 (39ad614)
  creationTimestamp: null
  labels:
    io.kompose.service: twitter-service
  name: twitter-service
spec:
  replicas: 1
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        io.kompose.service: twitter-service
    spec:
      containers:
      - command:
        - /go/twitter-service
        image: twitter-service
        name: twitter-service
        ports:
        - containerPort: 3000
        resources: {}
      restartPolicy: Always
status: {}
